### ISSUE TITLE
Newbie problem: I cannot uninstall

### ISSUE THREAD

**Issue by RoyTheNewbie** [snwh/suru-icon-theme#1]
I am sorry if my question is elementary: I am a novice, not a Ubuntu guru.. I am using Ubuntu 16.04.3 and the Unity desktop environment.

I thought I would try your themes so I followed the instructions for installing. I think there were a few error messages at that time, to the effect that various sizes of icons were not being installed. At least, that is how I remember it. Apart from that I coulld see that the installation seemed to have worked OK because I could see various icons in the title bar and the launcher had changed, I thought I would check that I could uninstall the themes but the uninstall failed: I got this error message:

$ make uninstall
rm -r ~/.local/share/icons/Suru
rm: cannot remove '/home/roy/.local/share/icons/Suru': No such file or directory
Makefile:15: recipe for target 'uninstall' failed
make: *** [uninstall] Error 1

Can you please tell me what I have done wrong and on how I can revert to the default Ubuntu icons?

**Comment by rafifos** [comment]
If Suru was installed with sudo, it's located in '/usr/share/icons/', just open nautilus as root (sudo nautilus) and go there, or run in a terminal 'sudo rm -r /usr/share/icons/Suru'

**Comment by snwh** [comment]
The `install: omitting directory` messages are nothing to worry about. If uninstall doesn't work it means that it wasn't installed at all. Does the folder "~/.local/share/icons` exist?

**Comment by snwh** [comment]
I pushed a fix to the Makefile that may help with this issue.

**Comment by RoyTheNewbie** [comment]
Thanks for responding so quickly.

Yes, the /.local/share/icons` does exist. However, there is nothing there for Suru.

I note your comment "The install: omitting directory messages are nothing to worry about. " Yes, that was exactly what I saw during the installation process. 
It occurs to me that I may have installed Suru "in the wrong place". I created a folder called Suru-themes in which I unzipped the file that I had downloaded from your website, and then ran the "make install" command in the terminal.

For your information, I have now figured out myself how to revert to the Unity icons that I had previously: I ran the command gsettings set org.gnome.desktop.interface icon-theme unity-icon-theme in the terminal. I later also found that I could use the Unity Tweak tool to do it. Most icons reverted to the way they were before the installation but there are icons in the main Ubuntu bar (like Calendar, Mail and the Wi-fi that are subtly changed. It's no big deal but it seems like I have been left with a small residue of Suru icons.
So really I have got myself back to where I want to be (with Unity icons) but I can select Suru icons if I wish. However, I just cannot uninstall Suru, as I described at the outset.

Right now I am left with Suru installed and I can select it if I wish in Unity Tweak.

**Comment by snwh** [comment]
All I can say is if neither `/usr/share/icons/Suru/` or `~/.local/share/icons/Suru` exist then this icon set isn't installed. The install commands only copies the icon set to either location and uninstall simply deletes the Suru folder at either location, so I don't know what may or may not have happened when you tried installing it.

**Comment by rafifos** [comment]
As I said, since it's not located on your HOME, you probably installed Suru with sudo..

Try running `sudo make uninstall-root`
