### ISSUE TITLE
Document viewer icon is only white when using an icon size < 50

### ISSUE THREAD

**Issue by Feichtmeier** [snwh/suru-icon-theme#10]
![bildschirmfoto von 2017-11-25 11-28-26](https://user-images.githubusercontent.com/15329494/33229691-db449160-d1d3-11e7-8c2f-fb9c1b421b06.png)
![bildschirmfoto von 2017-11-25 11-28-32](https://user-images.githubusercontent.com/15329494/33229692-db5c1402-d1d3-11e7-9088-1b91009d7b76.png)

**Comment by snwh** [comment]
Yes, and it's not the only one to be "incomplete", this is an in-development theme after all. 😉

**Comment by snwh** [comment]
Is 48 the default size for the "dock"?? 64 would be much better.

**Comment by Feichtmeier** [comment]
Yeah it is : / 48!
Sorry, I thought one should report bugs here =D Didn't know you know allready. :) Happy weekend!

**Comment by snwh** [comment]
Fixed
