### ISSUE TITLE
Icons of Unstable Apps Design

### ISSUE THREAD

**Issue by eaglersdeveloper** [snwh/suru-icon-theme#112]
Google has long using different icons for different versions of Chrome.
Сorresponding labels are added to Beta and Dev icons:
![](https://i-cdn.phonearena.com//images/article/94984-image/Chrome-60-beta-for-Android-brings-new-search-widget-lots-of-API-improvements.jpg)

GNOME has also recently begun to unify icons of unstable applications:

![2018-10-27 15-22-47](https://user-images.githubusercontent.com/40228953/47604080-aef84d00-da05-11e8-990f-8cbcd62fc5a5.png)

How do you like it, Sam?

![unstable-apps-icons](https://user-images.githubusercontent.com/40228953/47603998-dd295d00-da04-11e8-82f4-f2f24879e7e1.png)

Each state of the unstable application corresponds to colors of the traffic light (except Nightly). Nightly blue as the evening sky.

**Comment by snwh** [comment]
### **Words should never appear in icons**

It's bad design and a translation nightmare.

Yes (as one of the folks at GNOME working on this) there is a style for unstable apps coming, but that's going to be handled by the shell and not in icons themselves.

This isn't something to be concerned with in the icons.
