### ISSUE TITLE
"cutted" trash icon in Nautilus Places sidebar

### ISSUE THREAD

**Issue by biancofla** [snwh/suru-icon-theme#12]
![nautilusplacesbar](https://user-images.githubusercontent.com/33801756/33240420-fce6be64-d2b5-11e7-8b33-9f9d08b7be61.png)

**Comment by snwh** [comment]
Hmm, the theme you're using mustn't have defined an `error_color` it should have a red ! there.

![screenshot from 2017-11-26 12-24-23](https://user-images.githubusercontent.com/1217306/33242545-cab1f80c-d2a4-11e7-9b27-f52426397cfe.png)

**Comment by snwh** [comment]
@biancofla there is a white one there 😂 
![screenshot from 2017-11-26 12-25-23](https://user-images.githubusercontent.com/1217306/33242558-ef8afab6-d2a4-11e7-93d5-0cc5e530a3b9.png)

**Comment by snwh** [comment]
I may have to re-think the full-trash icon.

**Comment by biancofla** [comment]
Ahahah I didn't expect this 
Btw, I'm using default Ubuntu theme

**Comment by snwh** [comment]
Fixed in latest commit
