### ISSUE TITLE
make: *** No rule to make target 'install'.  Stop.

### ISSUE THREAD

**Issue by wonkothesane42** [snwh/suru-icon-theme#14]
Hey mate, love the work your doing. I try to download the latest changes a few times a week now. Today when I tried to install I get the following error:

make: *** No rule to make target 'install'.  Stop.

Here's what I've been doing:

wget https://github.com/snwh/suru-icon-theme/archive/master.zip
unzip master.zip
cd suru-icon-theme-master
make install

I notice what looks like a change in the installation process, using a meson program now. Any chance you could elaborate on the instructions a little, I feel like some steps are being skipped and the newbies like me are now missing out. :)

Thanks
Wonko (going a little insane)

**Comment by snwh** [comment]
@wonkothesane42 yes, I've moved on from Make to Meson, the [readme](../blob/master/README.md) details the new installation process.

**Comment by snwh** [comment]
The best way to keep up with changes is to clone the git repo instead of wgetting the zip file every time.
```shell
git clone git@github.com:snwh/suru-icon-theme.git
```

**Comment by wonkothesane42** [comment]
Works like a charm now, thanks snwh!
