### ISSUE TITLE
"filled rubbish bin" icon implies that something is wrong

### ISSUE THREAD

**Issue by merlijn-sebrechts** [snwh/suru-icon-theme#16]
The icon for a filled rubbish bin looks as if something is wrong (there is a warning triangle on top of it).

![image](https://user-images.githubusercontent.com/1492981/34014007-ebb4f576-e119-11e7-9399-529f026558d5.png)

Other icon themes show this as a "fatter" bin:

![image](https://user-images.githubusercontent.com/1492981/34014070-1ec57170-e11a-11e7-91f4-5a8b93ea9d7a.png)

**Comment by merlijn-sebrechts** [comment]
Also, this is the first issue I made for an icon theme, so let me know if I'm doing this wrong ;)

**Comment by snwh** [comment]
@galgalesh this is pretty much how it goes. The full rubbish bin was changed not too long ago.
