### ISSUE TITLE
Green in battery icon unclear and possibly against Gnome design guidelines

### ISSUE THREAD

**Issue by merlijn-sebrechts** [snwh/suru-icon-theme#17]
Hi

*I'm really loving the icon theme! I'm going to use it as my daily driver for the following couple of days. Is it ok for you if I post the issues I find here?*

The "full battery" icon is a white battery filled with green. This is very hard for me to see in Ubuntu 17.10 because of the orange background. I'm red-green colorblind so the difference between Orange and Green is very hard for me to see, especially if it's such a tiny surface.

![image](https://user-images.githubusercontent.com/1492981/34042122-72d8deba-e19b-11e7-9089-7a96c24870e9.png)

Also, I think the gnome design guidelines require those icons to be monochrome.

**Comment by snwh** [comment]
Legibility and accessibility concerns like that have been among the reasons the GNOME panel has been solid black. Ubuntu appears to have done it's own thing again with regards to the panel and made it transparent without the necessary considerations, which is creating this visibility issue.

But you have a point about colour here, it's not sufficient enough to make this icon distinguishable.

For what it's worth, as someone who works on the GNOME icons they are not required to be monochrome. There are a handful of colors permitted for use in the icons: red, green, orange.

**Comment by merlijn-sebrechts** [comment]
@snwh 

The translucent top bar is actually a feature [introduced in upstream Gnome 3.26](https://help.gnome.org/misc/release-notes/3.26/):

> The top bar now becomes transparent when there aren’t any maximized windows. This is more attractive and gives a better sense of space.

The desktop team is doing great efforts to keep the delta with upstream GNOME as small as possible..

> For what it's worth, as someone who works on the GNOME icons they are not required to be monochrome. There are a handful of colors permitted for use in the icons: red, green, orange.

Then it might be best to take this into consideration when they choose the wallpaper for 18.04, so that the permitted colors are distinguishable enough from the wallpaper. Are these guidelines (permitted colors) written down somewhere?

**Comment by snwh** [comment]
@galgalesh I've already adjusted the icons and dropped the green.

**Comment by merlijn-sebrechts** [comment]
Great, thanks!

**Comment by snwh** [comment]
@galgalesh I'm behind following the GNOME changes. Themes still determine some aspects of the top bar, it appears that whichever theme you're using there haven't added the drop shadows behind the icon which would have retained contrast and visibility when the panel goes transparent (and the degree to which the panel goes transparent).

Adwaita for instance: 
![screenshot from 2017-12-18 11-47-15](https://user-images.githubusercontent.com/1217306/34117277-383c7b90-e3e9-11e7-9b0c-f947990cae3a.png)

**Comment by merlijn-sebrechts** [comment]
@snwh good catch! I'll file a bug for the Ambiance theme.

**Comment by merlijn-sebrechts** [comment]
Is it possible that this is an issue with the icon theme itself? This is my top bar with Adwaita.

![image](https://user-images.githubusercontent.com/1492981/34117523-4011b712-e41c-11e7-89fe-a3ed7948f39d.png)

Note that the slack icon does have a backdrop. This is the humanity icon set; those icons seem to have a slight backdrop.

![image](https://user-images.githubusercontent.com/1492981/34117620-7db6ca76-e41c-11e7-949f-7dd201305240.png)

**Comment by merlijn-sebrechts** [comment]
Scrap that, Just tested it in the "GNOME" session, there the icons do have a backdrop.
