### ISSUE TITLE
Backups Icon Suggestion

### ISSUE THREAD

**Issue by robertlarocca** [snwh/suru-icon-theme#18]
![backup-app](https://user-images.githubusercontent.com/29333852/34083762-ab020c54-e343-11e7-8d67-761dd0a504b5.png)

Suggestion for backup-app.png linked to org.gnome.DejaDup.png If approved an SVG will need to be created.

**Comment by snwh** [comment]
It's a bit too simplistic for a Suru icon.

**Comment by robertlarocca** [comment]
![backup-app](https://user-images.githubusercontent.com/29333852/34323012-375b77f6-e805-11e7-8153-dcccbbfd29c4.png)

What do you mean by a little to simple for Sure? Most of the icons are what I'd call extremely simply. For example the Help, Terminal, Calculator, clock. Do you have any ideas in mind?
