### ISSUE TITLE
"connected" wired network icon resembles an unplugged network port

### ISSUE THREAD

**Issue by merlijn-sebrechts** [snwh/suru-icon-theme#19]
![image](https://user-images.githubusercontent.com/1492981/34119345-13bb0168-e422-11e7-880f-576edf2cd862.png)

Possibly simply a missing icon: the "wired connected" icon looks like an empty socket.

**Comment by snwh** [comment]
This is the intended design

**Comment by merlijn-sebrechts** [comment]
My intuition is to think that my computer is disconnected because the socket is empty.. 

I first thought this icon had a "connected" variant where the socket is full, for example with a white square.

**Comment by snwh** [comment]
@galgalesh pushed a new design for these icons

**Comment by merlijn-sebrechts** [comment]
That is quick! <3

**Comment by mymike00** [comment]
oh, I really like the old icon... it could have the colors swapped, I mean the socket should be colored while around it transparent with maybe an external border...
