### ISSUE TITLE
Missing Transmission icon?

### ISSUE THREAD

**Issue by ricsipontaz** [snwh/suru-icon-theme#21]
The icon of Transmission looks very weird, maybe it's a fallback icon?

![kepernyokep errol 2017-12-18 22-01-13](https://user-images.githubusercontent.com/263398/34127921-23c99aca-e43f-11e7-9622-ccbf945a361f.png)

**Comment by snwh** [comment]
@ricsipontaz that appears to be an icon from the Humanity which is being used as a fallback, yes.

**Comment by snwh** [comment]
Should be fixed by inheriting Ubuntu mono
