### ISSUE TITLE
Missing Xiphos icon

### ISSUE THREAD

**Issue by ghost** [snwh/suru-icon-theme#22]
Hello,

Xiphos icon is missing :-)

http://xiphos.org/

Thanks

**Comment by snwh** [comment]
That's right, third-party application icons will be not be included. Infringing upon third-party brands is a no-no in this set.

**Comment by ghost** [comment]
It is a Gnome app under GPL licence, not some proprietary nor branded software ;)

**Comment by snwh** [comment]
It still has a brand regardless of whether it is open source or not. Icons for non-core, third party apps will not be included in this base set of icons.
