### ISSUE TITLE
Missing dconf Editor icon

### ISSUE THREAD

**Issue by robertlarocca** [snwh/suru-icon-theme#23]
![dconf-app 2](https://user-images.githubusercontent.com/29333852/34323007-17f9f4e6-e805-11e7-832e-ca7ddedc0a79.png)
![dconf-app 1](https://user-images.githubusercontent.com/29333852/34323008-180af8cc-e805-11e7-991e-cd1e00184b99.png)

**Comment by snwh** [comment]
added
