### ISSUE TITLE
Meson error: Not enough arguments to project(). Needs at least the project name and one language

### ISSUE THREAD

**Issue by wonkothesane42** [snwh/suru-icon-theme#24]
Hi there, pardon the dumb question, I'm new to meson. I tried to install latest version but get the following error when I run meson:

Not enough arguments to project(). Needs at least the project name and one language

here is what I do:

git clone https://github.com/snwh/suru-icon-theme.git
meson suru-icon-theme --prefix=/usr

I feel like I am not understanding instructions correctly or steps are missing. This is what I see in notes:

meson builddir --prefix=/usr
sudo ninja -C builddir install

Please help. 

Many thanks
Wonko

**Comment by dslul** [comment]
You need a more recent version of meson:
`sudo apt install python3-pip`
`pip3 install --user meson`

**Comment by wonkothesane42** [comment]
Thanks dslul, I got a little bit further:

After installing latest version of Meson I got this warning:
Successfully installed meson
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Nevertheless, I proceeded. Below is the output...

ubuntu@ubuntu:~/builddir$ meson suru-icon-theme --prefix=/usr
The Meson build system
Version: 0.44.0
Source dir: /home/ubuntu/builddir/suru-icon-theme
Build dir: /home/ubuntu/builddir
Build type: native build
Project name: suru-icon-theme
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program meson/post_install.py found: YES (/usr/bin/env python3 /home/ubuntu/builddir/suru-icon-theme/meson/post_install.py)
Build targets in project: 0
Found ninja-1.5.1 at /usr/bin/ninja
ubuntu@ubuntu:~/builddir$ sudo ninja -C suru-icon-theme install
ninja: Entering directory `suru-icon-theme'
ninja: error: loading 'build.ninja': No such file or directory
ubuntu@ubuntu:~/builddir$

**Comment by snwh** [comment]
Copying and pasting the commands *exactly* as they appear in the README should install everything without error.
