### ISSUE TITLE
Evolution icon incomplete for sizes <= 48x48

### ISSUE THREAD

**Issue by merlijn-sebrechts** [snwh/suru-icon-theme#25]
The icon `evolution.png`, in all of the folders 48x48 and downward is incomplete: it is just a blue squircle.

The same goes for the files `org.gnome.Evolution.png`, `internet-mail.png` and `mail-app.png`.

In the dock:

![image](https://user-images.githubusercontent.com/1492981/34654418-995a78a6-f3fb-11e7-9486-2139b1234786.png)

In the applications view:

![image](https://user-images.githubusercontent.com/1492981/34654494-d0c42016-f3fc-11e7-86c3-2ce5448e0457.png)

**Comment by mymike00** [comment]
yeah, this theme is under development. I think it's not the only icon that misses some size...

**Comment by snwh** [comment]
Fixed in latest

**Comment by Astrowatt** [comment]
I can see it now in latest update (10 Feb). Thanks @snwh !
