### ISSUE TITLE
Use aubergine (purple) as the folder icon color instead of orange

### ISSUE THREAD

**Issue by kq01526** [snwh/suru-icon-theme#27]
Hi,

in a a lot of themes today, blue is being used as the highlight color, incl. folder icons. This is easy on the eyes and looks good.

The Ubuntu theme on the other hand uses bright orange for highlights and folder icons. This is not easy on the eyes and does not look good (of course the latter can be subjective).

Why can't we change that to the official aubergine color(s) instead, which would be much easier on the eyes than orange, see:

https://design.ubuntu.com/brand/colour-palette/

?

**Comment by kq01526** [comment]
Also requested for communitheme: https://github.com/Ubuntu/gnome-shell-communitheme/issues/54

**Comment by kq01526** [comment]
Any update?

**Comment by snwh** [comment]
Nope, sticking with orange. Purple/aubergine is the Canonical brand colour whereas orange is the Ubuntu colour.
