### ISSUE TITLE
Missing Trash Can Icon

### ISSUE THREAD

**Issue by lukeblevins** [snwh/suru-icon-theme#28]
As of now, there is still no desktop trash icon present.

**Comment by snwh** [comment]
Yeah, I'm still trying to figure out how to do this one (to my satisfaction) in the Suru style

**Comment by snwh** [comment]
Added in latest version

**Comment by lukeblevins** [comment]
Still not present in latest communitheme. Are we waiting on the communitheme team to add this icon?
