### ISSUE TITLE
MimeType Icon Requests

### ISSUE THREAD

**Issue by ricvelozo** [snwh/suru-icon-theme#29]
- [x]  Rust: https://www.rust-lang.org/
- [x] JSON
- [x] YAML
- [x] Sass 
- [x] Go: https://golang.org/
- [x] Java package (application/x-java-archive)
- [x] C#

plain text, no media type
- INI 
- LESS
- TOML (used with Rust): https://github.com/toml-lang/toml

**Comment by snwh** [comment]
I don't think C# can have icons

**Comment by ricvelozo** [comment]
I don't think C# has a branding. Something like just "[C#](https://en.wikipedia.org/wiki/File:C_Sharp_wordmark.svg)", in a default style for similar icons.

**Comment by snwh** [comment]
@ricvelozo I added it as `text-c-sharp`, but I'd need to know the media type for c# files and I can't seem find one for C#, therefore it won't have a styled icon. (unless you can dig up the media type)

**Comment by snwh** [comment]
Same goes for LESS

**Comment by ricvelozo** [comment]
The GNOME Files shows `text/x-csharp`. For LESS, unfortunately, it's just text.

**Comment by snwh** [comment]
@ricvelozo how'd you determine that?

**Comment by ricvelozo** [comment]
In file properties view, in type column. The Faenza theme uses "text-x-csharp" for C#.

**Comment by inferno986return** [comment]
As someone who works with JSON frequently it would be good to see an icon for it. Maybe with the circular logo?

I would also request .ePub and .Mobi have icons if they haven't already. The ePub logo is a square swirl and the files are an open format.

It would be pretty cool to support file extensions for less common programming languages such as Swift, BASIC, Pascal, Fortran and COBOL.

Those are the file icons that immediately come to mind. I also want to say thank you for making Ubuntu looks much prettier and more contemporary.

- [x] epub
- [x] mobi
- [x] fortran
- [x] COBOL

not registered as a media type (therefore won't display an icon)
- BASIC
- Swift

**Comment by snwh** [comment]
@inferno986return sure, but some of these languages you mention don't have distinct logos or anything

**Comment by snwh** [comment]
I'm gonna lock this issue for now any further requests for mimetypes can be made: https://github.com/snwh/suru-icon-theme/issues/65

**Comment by snwh** [comment]
All requests here done :smile: closing
