### ISSUE TITLE
Border outline for smaller icons

### ISSUE THREAD

**Issue by PJ-Singh-001** [snwh/suru-icon-theme#3]
GREAT JOB! And Thank You. :)

Here is a suggestion...

The border on some of the smaller icons looks out of place...

As an example, the outline for the application-pdf.svg is a grey color. Maybe the outline should be a darker shade of the most prominent color in the icon.  In the case of application-pdf.svg, perhaps a dark red color?

Still you have to be careful not to use too dark a color.  For example, I think the folders.svg is on the right track, but the darker orange outline, of four the smaller sizes, may be a bit ~too~ dark, IMHO.

Is it possible to make the smaller icons exactly like the largest icon, and not put a border?  (Not sure if that will maintain enough contrast at the smaller sizes, but may be worth a try?)

**Comment by snwh** [comment]
Thanks, I have considered these things already. There's reasons for the colour choices for the borders/outlines – using black allows for the border to disappear when the icons are over a dark background:

![screenshot from 2017-10-21 13-29-13](https://user-images.githubusercontent.com/1217306/31854270-e55dcd96-b663-11e7-99c5-3ec9e0e58082.png)

Note the subtle difference in the PDF and the archive icon (which has a yellow border).

Mind you, I haven't completely decided whether to go with coloured or black (this theme is still in-development so things are subject to change.)
