### ISSUE TITLE
MIssing Icons

### ISSUE THREAD

**Issue by ghost** [snwh/suru-icon-theme#32]
These Icons are missing:
Backups
Clocks
Disk Usage Analyzer
Image Viewer
Logs
Power Statistics
Software Updater
Software & Updates
Startup Applications
Startup Disc Creator

Not sure about these (do these ones stay as they are?):
LibreOffice
Aisle Rot Solitaire
Shotwell
Mines
Synaptics Package Manager
Remmina
Gimp
Mahjongg

EDIT: Icons that are not missing anymore:
(Disks)
(Gnome To Do)
(Help)
(Screenshot)

**Comment by Feichtmeier** [comment]
I would like to add two more missing icons since the latest updates:

gnome-tweaks (I guess to the name change form gnome-tweak-tool to gnome-tweaks)
And the gnome settins app, no idea why, changed to the ubuntu-mono-dark icon

**Comment by uniquePWD** [comment]
Gedit is missing from the list.

**Comment by wandrewkeech** [comment]
The official policy is no third party apps, so even though some of these on the list are included on the image by default, I think it should look more like this (though I'm not an authority):

Backups `deja-dup`
~~Clocks `gnome-clocks`~~
Disks `gnome-disks`
Disk Usage Analyzer `baobab`
~~Gnome To Do `gnome-todo`~~
~~Help `gnome-help`~~
Image Viewer `eog` (variant of the `gnome-photos` icon ?)
Logs `gnome-logs`
Power Statistics `gnome-power-statistics`
Screenshot `gnome-screenshot`
Software Updater `update-manager`
Software & Updates `software-properties-gtk`
Startup Applications `gnome-session-properties`
Startup Disk Creator `usb-creator-gtk`
~~Text Editor `gedit`~~

Synaptic `synaptic` isn't default, but I'm not sure if it's truly third party or not.

**Comment by uniquePWD** [comment]
Gedit can be removed from the list.

**Comment by skewty** [comment]
Templates folder is missing

**Comment by snwh** [comment]
- [x] Backups `deja-dup`
  - [x] Clocks `gnome-clocks`
  - [x] Disks `gnome-disks`
  - [x] Disk Usage Analyzer `baobab`
  - [x] Gnome To Do `gnome-todo`
  - [x] Help `gnome-help`
  - [x] Image Viewer `eog` (variant of the `gnome-photos` icon ?)
  - [x] Logs `gnome-logs`
  - [x] Power Statistics `gnome-power-statistics`
  - [x] Screenshot `gnome-screenshot`
  - [x] Software Updater `update-manager`
  - [x] Software & Updates `software-properties-gtk`
  - [x] Startup Applications `gnome-session-properties`
  - [ ] Startup Disk Creator `usb-creator-gtk`
  - [x] Text Editor `gedit`
  - [x] Templates `folder-templates`

**Comment by snwh** [comment]
Synaptic is a no. (How this app is still around in the terrible shape it's in is a mystery to me)

**Comment by Feichtmeier** [comment]
Two minor additional icons that are "missing":
- package icon (for example in the Ubuntu system updater there are packages listed if updates are available)
- extension icon for example in gnome to do  settings

:) Awesome work so far thank you very much

**Comment by jason-gu** [comment]
Missing Icon:
Go - golang.org

**Comment by snwh** [comment]
Y'all this isn't a dumping ground for all missing icons. I'm closing this issue. 

**FILE ISSUES FOR MISSING ICONS INDIVIDUALLY AND NOT IN MASSIVE LISTS PLEASE AND TY**
