### ISSUE TITLE
Does Suru's GPL licence allows us to create own third-party icons for exclusive, private and unshareable use (I mean only for me)?

### ISSUE THREAD

**Issue by gusbemacbe** [snwh/suru-icon-theme#38]
As third-party icons are not allowed for Suru icons theme, but does its GPL licence allow me to fork this repository, to create own third-party icons for and exclusive and private use (I mean only for me) and not to share the icons to the public, or am I required to publish and share the derived Suru icons theme in another place (I mean in mine, not in your place, so you do not allow)?

**Comment by snwh** [comment]
The GPL license is meant largely for the source code of the icons, scripts and other code. The PNG assets (the icons themselves are Creative Commons licensed) –I cleared this up a bit in the README. Whatever you do with your private copy is fair use, you only need to worry about licensing if you plan to redistribute the icons.
