### ISSUE TITLE
How about to insert Monero and Crypto icons in the theme?

### ISSUE THREAD

**Issue by cialu** [snwh/suru-icon-theme#41]
Hi,
due to crypto diffusion and to many wallet and node GUI client available for Linux, how about to insert Monero and major cryptocurrencies icons in the theme?

I mean only the most important and full opensource cryptocurrencies like Monero, Bitcoin, Litecoin, ZCash and just few more.

**Comment by snwh** [comment]
These are third party applications and, like all others, icons for them will not be included in this theme.
