### ISSUE TITLE
Aliasing makes non-straight lines in symbolic icons appear thinner/less contrasty

### ISSUE THREAD

**Issue by ya-d** [snwh/suru-icon-theme#46]
_Coming from a [discussion about GTK window controls](https://github.com/ubuntu/gtk-communitheme/issues/369#issuecomment-385195771) in Communitheme. I couldn't find this issue being reported/discussed before._

Because of aliasing diagonal lines in symbolic icons look thinner and less contrasty compared to straight (vertical/horizontal) lines.

This is especially noticeable for window controls, with the X (close button) right next to minimize and close. It makes the close button look darker and makes it kind of vanish into the background -- which gets worse against lower contrast backgrounds (like orange or lighter grey). The same effect is visible for other icons with non-straight lines like the magnifying glas though. Maybe this can be offset visually by making non-straight strokes a little bit thicker.

<img width="751" alt="contrast-window-controls-2" src="https://user-images.githubusercontent.com/30781876/39405226-e215ebb8-4ba1-11e8-9197-9c7a8677b1bb.png">

<img src="https://user-images.githubusercontent.com/30781876/39405266-8e3955e2-4ba2-11e8-9501-2d0b088395cb.gif"> <img src="https://user-images.githubusercontent.com/30781876/39405279-bbdf819c-4ba2-11e8-8a50-e85ebbde674a.gif">
_(gifs provided by @godlyranchdressing)_

**Comment by snwh** [comment]
This is unavoidable. There will always be aliasing artifacts for any diagonal (or curved) line. Contrast issues have more to do with competing colours than stroke widths, I propose removing the bright orange from the background of the button because a) oranges and reds are conventionally warning or error colours and b) the colour isn't adding extra any meaning to the icon here so it's pretty extraneous.

**Comment by snwh** [comment]
Adjusted in https://github.com/snwh/suru-icon-theme/commit/654e9c339f2f2f049e51fe11d78f2c45df99dbee but I suspect the problem will persist.

**Comment by ya-d** [comment]
Thanks for your reply! While it can’t be avoided technically shouldn’t we care for the visible result? Type designers for example spend a lot of time [compensating](http://designwithfontforge.com/en-US/Trusting_Your_Eyes.html) for human perception or technical limitations in print or display. To my eye this isn’t related to the contrast against the background alone, it only increases the problem.

As I was just about to write this and point to [this tip](https://davidwalsh.name/6-tips-designing-crisp-readable-icons) to slightly offset the diagonals, you already committed a patch. Thanks!

**Comment by snwh** [comment]
@ya-d yes and competent icon designers like myself do the same for icons–I completely care about the visual result. Unlike typefaces, icons don't get anti-aliased by the system, at least not yet.

**Comment by ya-d** [comment]
Yeah, sorry, I did not want to be presumptuous or instructive. I was interrupted by your commit and would have noted that otherwise. I couldn't express myself clearer without those links as I'm not a designer. Cheers! 😉
