### ISSUE TITLE
icones are missing 

### ISSUE THREAD

**Issue by ghost** [snwh/suru-icon-theme#47]
I've noticed that some icons are missing in various application such as Synaptic.
![capture du 2018-05-02 23-31-20](https://user-images.githubusercontent.com/38924317/39550328-220db8e2-4e61-11e8-92e4-0a488f2c053e.png)

**Comment by mahmud2011** [comment]
Software Updater icon is missing.

![screenshot from 2018-05-27 01-08-15](https://user-images.githubusercontent.com/5278142/40579510-8dc25312-614a-11e8-92e7-87533f73a5ef.png)

**Comment by snwh** [comment]
duplicate of #32
