### ISSUE TITLE
[Missing Icon] Gnome Usage

### ISSUE THREAD

**Issue by PlugaruT** [snwh/suru-icon-theme#48]
![screenshot from 2018-05-16 20-48-57](https://user-images.githubusercontent.com/6437932/40134284-9d785c46-594a-11e8-8ea4-68ad42db9f68.png)

**Comment by snwh** [comment]
Added in b7807550fe527691483d5cd1219339fbea05912b

**Comment by PlugaruT** [comment]
The icon looks dope :+1:
