### ISSUE TITLE
[Missing Icon] Gnome Settings

### ISSUE THREAD

**Issue by PlugaruT** [snwh/suru-icon-theme#49]
![screenshot from 2018-05-16 21-00-54](https://user-images.githubusercontent.com/6437932/40134835-40f6c942-594c-11e8-8197-0dbae87a020f.png)

**Comment by snwh** [comment]
Can't confirm that this icon is missing.

**Comment by PlugaruT** [comment]
Weird. Using the Communitheme the icon for the settings if the one from the image above.

**Comment by snwh** [comment]
Oh that'll do it. The communitheme package (which is very much beta) is not necessarily the latest version of the theme.
