### ISSUE TITLE
Is this ongoing

### ISSUE THREAD

**Issue by uniquePWD** [snwh/suru-icon-theme#5]
Or has work ceased?

**Comment by xelius** [comment]
If you care and want to speed things up there is a [Patreon](https://www.patreon.com/snwh).
cheers

**Comment by snwh** [comment]
No not dead, but I wrote a post on Google+ a couple months ago saying that some of my projects have been put on the back burner.

**Comment by mymike00** [comment]
I think this issue can be closed...
lots of work done in the last days :heart_eyes:

**Comment by snwh** [comment]
@mymike00 been reinvigorated by the moves towards it being the default in Ubuntu
