### ISSUE TITLE
Change the busy spinner

### ISSUE THREAD

**Issue by madsrh** [snwh/suru-icon-theme#52]
Hi

As discussed [here](https://community.ubuntu.com/t/cursor-theme-discussion/3870/87) could the theme include a blue version of the “process-working-symbolic” icon as busy spinner?

I know that it's an indicator within the UI, but that doesn't matter IMO. 

Frederik writes:
> Could you please include the blue progress working indicator in the suru icon theme? The blue fits in the unity8 spirit we tried to revive with the communitheme (that’s actually only the working title ;)). All progress bars are blue.
If this is really no option for you then maybe you could adapt your indicator (the black spinning disk without the cursor above it) to the blue Nr 13 from the communitheme cursor set?

![image](https://user-images.githubusercontent.com/3986894/40971447-f510b318-68bd-11e8-88f3-c254f4f6efe2.png)

**Comment by snwh** [comment]
Done and done
