### ISSUE TITLE
Migrate to another platform (Gitlab or another) to keep things moving

### ISSUE THREAD

**Issue by julian-alarcon** [snwh/suru-icon-theme#53]
Hi!

You should consider the migration to another platform after the MS announcement of the acquisition of GitHub.
http://www.itprotoday.com/open-source/why-open-source-software-moving-gitlab-after-microsoft-github-deal
https://www.bleepingcomputer.com/news/technology/gitlab-sees-huge-traffic-spike-after-news-of-microsoft-buying-github/
https://dev.to/maxart2501/what-i-think-is-bad-about-microsoft-acquiring-github-gme
https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers/
https://blog.github.com/2018-06-04-github-microsoft/

**Comment by snwh** [comment]
Why?

GitLab is still a centralized system and hosted on cloud infrastructure owned by one of these massive corporations (currently *Microsoft* Azure, migrating to Google Cloud) unless I completely decentralize or self-host git, all this hand-wringing is moot and silly in my view.

This isn't 1996, Microsoft is being a good open source citizen these days and it purchasing GitHub likely saved the company.
