### ISSUE TITLE
google-chrome can not be started with the suru cursor selected

### ISSUE THREAD

**Issue by Feichtmeier** [snwh/suru-icon-theme#55]
- download google-chrome deb (67)
- clone & build suru repo with usr prefix
- select the suru cursors
- start google-chrome 

I tried to find any other .deb that can't be started with the suru cursors selected but didn't find any, yet.
:man_shrugging: 
Edit: checked the chromium snap --> the issue does not occur

**Comment by snwh** [comment]
Highly unlikely that this is a bug in the cursor set itself, given how they're just image files.

**Comment by Feichtmeier** [comment]
Okay, fixed with the latest pull, no idea what caused this!
