### ISSUE TITLE
Missing Icon: shotwell

### ISSUE THREAD

**Issue by Feichtmeier** [snwh/suru-icon-theme#60]
![image](https://user-images.githubusercontent.com/15329494/41625103-ee8efce2-7417-11e8-8723-650645f6b355.png)

It comes pre-installed with ubuntu. :man_shrugging:

**Comment by snwh** [comment]
Shotwell is a dead project :man_shrugging:, it died when the Yorba project ended I dunno why ubuntu still ships it. Heck, elementary forked it to make Pantheon Photos and GNOME is focused on GNOME Photos.

The Ubuntu default install should really be move to using the GNOME Core apps

**Comment by Feichtmeier** [comment]
That's correct. I am not a fan by that "old" apps neither. Yet, it's pre-installed in 18.04 and probably it will be in 18.10. I can open a suggestion on the hub for changing it to gnome photos but I really don't know if this will happen.

**Comment by snwh** [comment]
I think that shipping those old apps lent to the general sense that the Ubuntu desktop stagnated.

**Comment by Feichtmeier** [comment]
Good argument, I will open a suggestion and steal it! :dancer:

**Comment by snwh** [comment]
@Feichtmeier same goes for Rhythmbox. GNOME Music is really where the focus is.

**Comment by Feichtmeier** [comment]
I am already typing on the thread! Yet, would you rather like to see them "unthemed"? There is a realistic chance that they could be dropped for 18.10 but 18.4 is already released and the communitheme snap (and within the snap your icon theme) can be installed on 18.4 and will be promoted to do so in the future

**Comment by Feichtmeier** [comment]
https://community.ubuntu.com/t/18-10-suggestion-drop-old-apps-and-go-full-gnome/6622

**Comment by Feichtmeier** [comment]
Hey @snwh :)
I tried my best but old people keep swarming those threads that mistake look and feel with design and think having 100s of photos loaded from the camera from usb is the average use case for a photos app in 2018.

**Comment by snwh** [comment]
Welcome to my constant struggle as a FOSS designer, we’re always on the defensive. FOSS users are especially resistant to change and constantly conflate look and feel with usability. 

I lost the will to participate in community  discussions years ago because I get swamped with arguments.

**Comment by Feichtmeier** [comment]
I can try to make those two icons with your icon guidelines. Shall I just push them to our fork or would you welcome a PR (if the quality is on the needed level)?

**Comment by snwh** [comment]
If anything it'd just be  a symlink to the existing music and photos icons.

**Comment by Feichtmeier** [comment]
Uhh okay, I was already trying:
![image](https://user-images.githubusercontent.com/15329494/41667157-922c9492-74ac-11e8-9ea3-8dda573c8da7.png)

But great to read, then I will make a PR with that symlink script!
