### ISSUE TITLE
Missing Icon: rhythmbox

### ISSUE THREAD

**Issue by Feichtmeier** [snwh/suru-icon-theme#62]
![image](https://user-images.githubusercontent.com/15329494/41625344-cdbe81d0-7418-11e8-89cc-e566550bb40a.png)

Ubuntu default music/media player :man_shrugging: (not my personal fav :D, but it comes installed by default)

**Comment by eaglersdeveloper** [comment]
Rhythmbox is a "third-party" app.

[CONTRIBUTING.md](https://github.com/snwh/suru-icon-theme/blob/master/CONTRIBUTING.md#third-party-icons):
> The Suru icon set is not a "universal" set and **will not attempt to supply icons for "third-party" applications.** A "third-party" application is any application that is non-generic and has it's own branding, e.g. Mozilla Firefox or Inkscape.

**Comment by Feichtmeier** [comment]
Okay, despite the *heavy* branding of rhythmbox it is preinstalled in Ubuntu. Would an official agreement of the app contributors help here? Otherwise I see no real solution except provide an icon for it in the fork of suru which we use in the communitheme name space, which would be kind of odd, and we were successful to avoid this until now.

**Comment by Feichtmeier** [comment]
That's right and good!
But is rhythmbox really a third party? I don't think gnome officially declared gnome music as their official music app or did they? It's not like I want to try to force anything here, I am really not a fan of the application myself =]
I am (one of them) developing the communitheme (working title) theme and we want the best possible look for Ubuntu. That's all

**Comment by Ads20000** [comment]
> To start, we can try to make that not adapted icons are automatically insert inside the shape...

This sounds great, should I file an Issue for it? :)

**Comment by eaglersdeveloper** [comment]
Here already needs support from system.
