### ISSUE TITLE
Template and its license

### ISSUE THREAD

**Issue by eaglersdeveloper** [snwh/suru-icon-theme#64]
[Template.svg](https://github.com/snwh/suru-icon-theme/blob/master/src/fullcolor/Template.svg) will be hard to use to create icons in Suru style.

I suggest edit the template by adding a form:
![](https://snwh.org/images/suru/guidelines/outlines-light.png)
Still need to solve the problem of license. The current template is licensed under the GPL license, which limits its using in most programs.

**Comment by snwh** [comment]
Fair, what exactly is the licensing issue? The template itself isn't meant to be included with apps.

**Comment by eaglersdeveloper** [comment]
Really? How developers can create app icons specifically for Ubuntu?

**Comment by snwh** [comment]
@eaglersdeveloper render the PNG icons and include those? The template isn't the icons it's just the source. What is the issue with it being GPL? If an app were closed source they wouldn't ship the icon's source template anyway.

**Comment by eaglersdeveloper** [comment]
@snwh I'm not a lawyer, but I believe that the requirements of the GPL license extend to derived files from the source code. If I export the picture to PNG, it will still be licensed under the GPL.

**Comment by snwh** [comment]
Well, you can't apply the GPL to an image the way you can to code. But I'm happy to adjust overall licensing of the SVG sources.

**Comment by snwh** [comment]
Updated to clarify that the svg files are cc-by-sa
