### ISSUE TITLE
Missing Icon: startup disk creator

### ISSUE THREAD

**Issue by eaglersdeveloper** [snwh/suru-icon-theme#66]
Icon name: `usb-creator-gtk`

![2018-06-25 15-51-18](https://user-images.githubusercontent.com/40228953/41849119-de43d998-7890-11e8-9d99-e4dbbad331c6.png)

**Comment by snwh** [comment]
inspiration for how to do that one (well) in Suru style hasn't struck me yet

**Comment by snwh** [comment]
Fixed in 2d8102084eaf194f04076ec6949feacb0eb4a1ba

**Comment by mymike00** [comment]
so this can be closed
