### ISSUE TITLE
Missing Icon: amazon?

### ISSUE THREAD

**Issue by eaglersdeveloper** [snwh/suru-icon-theme#68]
Icon name: `amazon-store`

![2018-06-26 17-52-06](https://user-images.githubusercontent.com/40228953/41917057-8d7cbb6c-796a-11e8-8ab8-06292672e332.png)

I know that icons for third-party apps don't pass to Suru.
But you need penetrate into the details.

Amazon in Ubuntu is a web app by Canonical. More precisely, it's a .desktop shortcut, which opens Amazon in default browser. In URL added Canonical's refferal tag, When you buy in Amazon that started from shortcut, Canonical get a tiny % of the sale price.

I put a question mark at issue name end, because my opinion can don't coincide with @snwh opinion.

Source: [Omg! Ubuntu!](https://www.omgubuntu.co.uk/2017/06/ubuntu-amazon-web-app-is-staying)

### My icon
[amazon-store.svg](https://gist.github.com/eaglersdeveloper/05bf9dbbc30345395d377d2d72df595f)

![suru](https://user-images.githubusercontent.com/40228953/41918096-ae2cdcaa-796c-11e8-9644-055f95dfb269.png)

**Comment by snwh** [comment]
:thinking:

**Comment by snwh** [comment]
If it were to be added it would have to be on a plain white icon and ZERO modification to the Amazon logo.

**Comment by eaglersdeveloper** [comment]
Hmm... OK! :ok_hand:

**Comment by eaglersdeveloper** [comment]
I have removed the shadow and changed background color to white `#ffffffff`.
The same link: [amazon-store.svg](https://gist.github.com/eaglersdeveloper/05bf9dbbc30345395d377d2d72df595f)

![amazon-store](https://user-images.githubusercontent.com/40228953/42019091-35ce1940-7ac5-11e8-8f84-7ffa07d7dd57.png)

**Comment by snwh** [comment]
You know there's this mechanism called pull-requests :wink:

**Comment by snwh** [comment]
But I've added one: https://github.com/snwh/suru-icon-theme/blob/f9e6a9957b7db6a6468476ca92c7078b68fac31a/Suru/256x256/apps/amazon-store.png

**Comment by eaglersdeveloper** [comment]
The icon in application menu will be different from the icon in Dock and App Panel, you know about it?

**Comment by snwh** [comment]
Yeah, that's fine
