### ISSUE TITLE
Missing Icon: input method

### ISSUE THREAD

**Issue by eaglersdeveloper** [snwh/suru-icon-theme#71]
Icon name: `input-keyboard`

![2018-06-27 11-26-19](https://user-images.githubusercontent.com/40228953/41959192-522745bc-79fd-11e8-905a-5508b477ba6e.png)

At the moment, icon with same name from `devices` folder uses.

**Comment by snwh** [comment]
That apps uses the `input-keyboard` icon, I can't change that.
