### ISSUE TITLE
icon for folders with files

### ISSUE THREAD

**Issue by jnlucian** [snwh/suru-icon-theme#73]
currently folders suru have no difference when has files and are empty, users coming Windows are already familiar with that action, so it would help consider the icon at least with the same effect of trash when is empty or full.

**Comment by snwh** [comment]
Well that's not a thing that the file manager does. There is no distinction between a folder with files and a folder without, so there's no icon to that effect.

You may want to take this up with the Nautilus developers: https://gitlab.gnome.org/GNOME/nautilus :wink:
