### ISSUE TITLE
Cursors for Windows

### ISSUE THREAD

**Issue by Niroa95** [snwh/suru-icon-theme#77]
How can I use the cursor theme for Windows? I know there is a file called w32-make.sh inside /src/cursors/
that generates a cursor for windows but I have no idea on how to run it. Can somebody help me, please?

**Comment by snwh** [comment]
The windows cursors are already made, they're the *.cur files in: https://github.com/snwh/suru-icon-theme/tree/master/Suru/cursors

**Comment by snwh** [comment]
Though running the script is as simple as `./w32-make.sh`

**Comment by Niroa95** [comment]
I can't seem to be able to execute that on the terminal, I copied the .cur from the folder into windows/cursors and then applied the theme. They seem a bit bigger than the usual, is there a way to make them smaller?

**Comment by snwh** [comment]
I have no clue, I'm not familiar with the mechanics of Windows cursors.
