### ISSUE TITLE
tweak tool icon sizes

### ISSUE THREAD

**Issue by mymike00** [snwh/suru-icon-theme#8]
The 32x32 tweak tool icon has 4 slider while the 48x48 only 3.
I think this shouldn't happen: a smaller icons has more details than a bigger one.
the 32x32 should have only 3 slider (and maybe the 48x48 4 sliders)
32x32 (https://github.com/snwh/suru-icon-theme/blob/master/Suru/32x32%402x/apps/tweaks-app.png)
![tweaks-app](https://raw.githubusercontent.com/snwh/suru-icon-theme/master/Suru/32x32%402x/apps/tweaks-app.png)
48x48 (https://github.com/snwh/suru-icon-theme/blob/master/Suru/48x48%402x/apps/tweaks-app.png)
![tweaks-app](https://raw.githubusercontent.com/snwh/suru-icon-theme/master/Suru/48x48%402x/apps/tweaks-app.png)

**Comment by snwh** [comment]
It may shock you, but the 16x16 icon has only 2 https://raw.githubusercontent.com/snwh/suru-icon-theme/master/Suru/16x16/apps/tweaks-app.png

**Comment by snwh** [comment]
But I hear you, this theme is a work-in-progress and I'm not that fond of the Tweaks icon –it's over complicated– so it's likely to change completely.

**Comment by snwh** [comment]
fixed
