### ISSUE TITLE
Request for Ubuntu icon (usage tbc) for Communitheme

### ISSUE THREAD

**Issue by ubuntujaggers** [snwh/suru-icon-theme#80]
Hi @snwh,

I intended to create this as a PR but the button is greyed out (apologies if I'm doing something wrong, I'm new to GitHUb).

There's some agreement on [the "call for participation" thread](https://discourse.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545) that it would be good to have a Suru icon for the Ubuntu logo ("Circle of Friends").  Then the icon can go at the top of the launcher by default, and the issue of branding the Gnome shell becomes less thorny, because there's a prominent Ubuntu logo at the top left of the screen (unless the user wants to remove it).

![Mockup](https://ubuntucommunity.s3-us-east-2.amazonaws.com/original/2X/1/1f9079a12b534a9fde76c7a69dc6451a9e1b5c1e.png)

There's still some discussion about what app it should link to.  For instance, didrocks suggested the Welcome app.  frederik-f suggested _"we could use this in your PR with some generic icon name and then symlink it to the icon we’d decided on in the future"_ but, as I say, I don't seem able to create a pull request  :(

If you can point me towards an svg for the Software Centre icon, I can make an svg in Inkscape for completion - I created these directly from the pngs of Software centre and hope they're pretty much "pixel perfect" for Suru:

**16 x 16px, normal and 2x size:**

![image](https://user-images.githubusercontent.com/38893390/43045928-3e5ec7ec-8db9-11e8-9064-331939f8d269.png)

![image](https://user-images.githubusercontent.com/38893390/43045937-66c43532-8db9-11e8-935e-ee635553964c.png)

**24 x 24px, normal and 2x size:**

![image](https://user-images.githubusercontent.com/38893390/43045942-7a1ed556-8db9-11e8-907f-69e7d4abb7bb.png)

![image](https://user-images.githubusercontent.com/38893390/43045944-7e647a76-8db9-11e8-8db6-c86fe2ba0821.png)

**32 x 32px, normal and 2x size:**

![image](https://user-images.githubusercontent.com/38893390/43045947-89bf4dec-8db9-11e8-977c-b9cb41c879a7.png)

![image](https://user-images.githubusercontent.com/38893390/43045948-8f87aa6c-8db9-11e8-8d15-0b0d197a37ae.png)

**48 x 48px, normal and 2x size:**

![image](https://user-images.githubusercontent.com/38893390/43045953-9e5a3f6e-8db9-11e8-95a8-e972a025eee6.png)

![image](https://user-images.githubusercontent.com/38893390/43045954-a12aa792-8db9-11e8-8246-039d518b3303.png)

**256 x 256px, normal and 2x size:**

![image](https://user-images.githubusercontent.com/38893390/43045957-ac5334ea-8db9-11e8-8c81-11b2af636691.png)

![image](https://user-images.githubusercontent.com/38893390/43045959-b0d92c7c-8db9-11e8-82a9-c089f261fcdc.png)

I can also provide the original pngs if uploading them has resulted in the loss of any quality or colour information, although I can't see any change in these embedded ones.

Please let me know if there's anything wrong here, happy to address any problems.

**Comment by snwh** [comment]
What is the name of the welcome app?

**Comment by snwh** [comment]
> I can also provide the original pngs if uploading them has resulted in the loss of any quality or colour information, although I can't see any change in these embedded ones

@ubuntujaggers GitHub will have compressed the PNG files here.  New icons for inclusion must come in the form of an SVG to be included in [src](https://github.com/snwh/suru-icon-theme/tree/master/src/fullcolor), and would be nice to receive as a pull request.

To pull request you need to have forked the repository and committed your changes in git.

**Comment by ubuntujaggers** [comment]
Okay - I found the svg of the different sizes for Software Centre and it would have been five mins of a job to re-make my logo as an svg.  However, I think your design works really nicely:

![image](https://user-images.githubusercontent.com/38893390/43046920-ea647aba-8dc7-11e8-8c99-c0c7687143d4.png)

Including the circle on a white background means it doesn't look too much like a clone of the Software Centre icon, even though they're both still orange.  So, that's a nice effect, and I guess I don't need to make an icon now  :)

I'm not sure it's 100% final that it will be used for the Welcome app btw (which I can't even find on my own install of Ubuntu).  It's more a case of making sure Ubuntu includes a Circle of Friends icon that can be used for "something" (tbc), and this does nicely IMO.

**Comment by eaglersdeveloper** [comment]
@snwh 
Is icon with the new computer pictogram suitable?
![2018-07-23 18-25-42](https://user-images.githubusercontent.com/40228953/43083885-93a0b0b8-8ea8-11e8-8c01-ca4f181f26e3.png)

**Comment by eaglersdeveloper** [comment]
@snwh, is icon with the new computer pictogram suitable?
![2018-07-23 18-25-42](https://user-images.githubusercontent.com/40228953/43084516-e521f6c6-8ea9-11e8-8703-a387ec1dd9ab.png)

**Comment by eaglersdeveloper** [comment]
@snwh, but the computer also refers to the pictogram. I can add a shadow.
