### ISSUE TITLE
Missing icon: Visual Studio Code workspace

### ISSUE THREAD

**Issue by merlijn-sebrechts** [snwh/suru-icon-theme#87]
Visual Studio Code Workspace files contain information about a workspace (i.e. project, solution, ..). Opening this file opens the workspace. Thus, it's common to browse to such a file using Files and open it to open the workspace. However, these files currently show as plain text files.

- media type: `plain text document (text/plain)`
- extension: `.code-workspace`

![image](https://user-images.githubusercontent.com/1492981/44650808-ef2c5680-a9e7-11e8-9356-24dd078a7d0b.png)

Visual Studio Code icons:

![image](https://user-images.githubusercontent.com/1492981/44651277-3109cc80-a9e9-11e8-8263-d870a4a63ac3.png)

Icon for the vscode workspace in Windows:

![image](https://user-images.githubusercontent.com/1492981/44840819-344bc500-ac42-11e8-99c9-86651b170eb1.png)

**Comment by snwh** [comment]
right, well the Code app icon won't be included as it's a third-party branded icon and the mimetype appears to not be supported by the mimetype library (whose name escapes me at the moment) so I'm afraid neither of these will be in the icon set.
