### ISSUE TITLE
Missing audio-volume-overamplified-symbolic (introduced by GNOME Shell 3.30)

### ISSUE THREAD

**Issue by didrocks** [snwh/suru-icon-theme#88]
### Icon Request

GNOME Shell 3.30 provides now an icon when you turn over-amplification of your sound settings in the OSD and top panel. This icon is named audio-volume-overamplified-symbolic.svg.
You can see the Adwaita version at https://gitlab.gnome.org/GNOME/adwaita-icon-theme/blob/master/Adwaita/scalable/status/audio-volume-overamplified-symbolic.svg.

Do you have time to provide one for the Suru icon theme?
Thanks!

**Comment by snwh** [comment]
Of course

**Comment by snwh** [comment]
Fixed in 172098e

**Comment by didrocks** [comment]
Thanks!
